spring:
  application:
    name: TestSwagger2 # 指定应用名称

server:
  port: 8083 # 指定该Eureka实例的端口号

#
#  #注册中心相关配置
#  eureka:
#    server:
#      # 配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔（5000ms）。
#      enable-self-preservation: false
#      eviction-interval-timer-in-ms: 5000
#    client:
#      # 不将自己注册到注册中心
#      register-with-eureka: false #fasle:
#      # 因为自己是注册中心，因此不用检索服务信息
#      fetch-registry: false        #true： Cannot execute request on any know server
#      # 注册中心的地址
#      service-url:
#        defaultZone: http://localhost:8080/eureka/
#    instance:
#      prefer-ip-address: true


eureka:
  client:
    fetch-registry: false # 注册中心职责是维护服务实例，false：不检索服务。
    register-with-eureka: false # 此应用为注册中心，false：不向注册中心注册自己。