spring:
  application:
    name: service-caller # 指定应用名称

eureka:
  instance:
    prefer-ip-address: true  # 是否显示主机的IP
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port} #将Status中的显示内容也以“IP：端口号”的形式显示
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082 # 指定该Eureka实例的端口号

ribbon:
  eureka:
    enabled: true
